services:
  - type: web
    name: tradexa-frontend
    runtime: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
